title: Désorde
DefaultContentLanguage: fr
baseURL: https://desorde.loupbrun.ca/
languageCode: fr
menu:
  main:
  - identifier: publications
    name: Publications
    title: Publications
    url: /p/
    weight: 10
#  - identifier: categories
#    name: Catégories
#    title: Catégories
#    url: /categ
#    weight: 20
  - identifier: napomo
    name: "napomo"
    title: "napomo"
    url: /napomo/
    weight: 20
  - identifier: a-propos
    name: À propos
    title: À propos
    url: /a-propos/
    weight: 30
paginate: 999
params:
  title: "Désorde"
  description: "Blogue de poésie"
  images:
    - /images/couverture.png
  author: Émile Brassard

theme: hugo-theme-desorde
