baseURL = "https://desorde.loupbrun.ca/"
languageCode = "fr"
DefaultContentLanguage = "fr"
title = "Désorde, par Émile Brassard"
theme = "hugo-theme-desorde"
paginate = 999

[author]
  name = "Émile Brassard"

# Catégories/étiquettes
[taxonomies]
  categ = "categ"

[menu]
  [[menu.main]]
  identifier = "publications"
  title = "Publications"
  name = "Publications"
  url = "/p"
  weight = 10

  [[menu.main]]
  identifier = "categories"
  title = "Catégories"
  name = "Catégories"
  url = "/categ"
  weight = 20

  [[menu.main]]
  identifier = "a-propos"
  title = "À propos"
  name = "À propos"
  url = "/a-propos/"
  weight = 30


