backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "static/images" # Media files will be stored in the repo under images/uploads

collections:
  - name: "contenu" # Used in routes, e.g., /admin/collections/blog
    label: "Contenu" # Used in the UI
    folder: "content/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug (nom de fichier)", name: "slug", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "a-propos" # Used in routes, e.g., /admin/collections/blog
    label: "À propos" # Used in the UI
    folder: "content/a-propos/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug (nom de fichier)", name: "slug", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}